//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserMVC.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [Key]
        public int UserID { get; set; }
        [Display(Name = "Full Name")]
        public string FullName { get; set; }
        [Display(Name = "Phone No")]
        public string PhoneNo { get; set; }
        [Display(Name = "Email Address")]
        public string Email { get; set; }
        [Display(Name = "DOB")]
        public System.DateTime Dob { get; set; }
        [Display(Name = "Role Name")]
        public int RoleID { get; set; }
        [Display(Name = "Gender")]
        public int GenderID { get; set; }
        public Nullable<int> UserStatus { get; set; }

        public virtual Role RoleGet { get; set; }
    }
}
